const DBCollections = Object.freeze({
  USER: 'User',
  STUDENT: 'Student',
  STAFF: 'Staff',
  DORM: 'Dorm',
  BLOCK: 'Block',
  ROOM: 'Room',
  BED: 'Bed',
  EQUIPMENT_CATEGORY: 'EquipmentCategory',
  EQUIPMENT_TEMPLATE: 'EquipmentTemplate',
  ROOM_EQUIPMENT: 'RoomEquipment',
  EQUIPMENT_HISTORY: 'EquipmentHistory',
  ROOM_TYPE_EQUIPMENT_CONFIG: 'RoomTypeEquipmentConfig',
  BOOKING_REQUEST: 'BookingRequest',
  CONTRACT: 'Contract',
  ROOM_TRANSFER_REQUEST: 'RoomTransferRequest',
  CONTRACT_EXTENSION: 'ContractExtension',
  BEHAVIORAL_SCORE_HISTORY: 'BehavioralScoreHistory',
  VIOLATION_REPORT: 'ViolationReport',
  PENALTY: 'Penalty',
  PRICING_CONFIG: 'PricingConfig',
  INVOICE: 'Invoice',
  INVOICE_LINE_ITEM: 'InvoiceLineItem',
  PAYMENT: 'Payment',
  VISITOR_REQUEST: 'VisitorRequest',
  VISITOR: 'Visitor',
  VISITOR_CHECKIN: 'VisitorCheckin',
  MAINTENANCE_REQUEST: 'MaintenanceRequest',
  MAINTENANCE_FEEDBACK: 'MaintenanceFeedback',
  OTHER_REQUEST: 'OtherRequest',
  ROOM_INSPECTION: 'RoomInspection',
  INSPECTION_EQUIPMENT_DETAIL: 'InspectionEquipmentDetail',
  NOTIFICATION: 'Notification',
  CHAT_CONVERSATION: 'ChatConversation',
  CHAT_MESSAGE: 'ChatMessage',
  NEWS: 'News',
  SYSTEM_CONFIG: 'SystemConfig',
  FACE_EMBEDDING: 'FaceEmbedding',
  STUDENT_ACCESS_LOG: 'StudentAccessLog',
  CAMERA_CONFIG: 'CameraConfig',
  EW_USAGE: 'EWUsage',
});

module.exports = {
  DBCollections,
};
